using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;
namespace Cpp.Api.Controllers;

[ApiController, Route("api")]
public class PortalController(AppDb db, IOrderRuleService rules, IFulfillmentGateway fulfillment) : ControllerBase
{
    static readonly CurrentUser DemoUser = new("u1", "RVERVE13", "Riley Verve", "Administrator", true, true);
    [HttpGet("current-user")] public object CurrentUser() => DemoUser;
    [HttpGet("accounts")] public async Task<object> Accounts() => await db.Accounts.OrderBy(x => x.Name).ToListAsync();
    [HttpGet("accounts/{id}")] public async Task<ActionResult<Account>> Account(string id) => await db.Accounts.FindAsync(id) is { } a ? a : NotFound();
    [HttpPost("accounts")] public async Task<IActionResult> CreateAccount(AccountRequest request) { var error = await ValidateAccount(request); if (error is not null) return BadRequest(new ProblemDetails { Title = "Account validation failed", Detail = error }); var idBase = new string(request.Name.ToLowerInvariant().Where(char.IsLetterOrDigit).Take(18).ToArray()); if (string.IsNullOrWhiteSpace(idBase)) idBase = "account"; var id = idBase; var suffix = 1; while (await db.Accounts.AnyAsync(x => x.Id == id)) id = $"{idBase}-{suffix++}"; var account = MapAccount(new Account { Id = id }, request); db.Accounts.Add(account); await db.SaveChangesAsync(); return CreatedAtAction(nameof(Account), new { id = account.Id }, account); }
    [HttpPut("accounts/{id}")] public async Task<IActionResult> UpdateAccount(string id, AccountRequest request) { var account = await db.Accounts.FindAsync(id); if (account is null) return NotFound(); var error = await ValidateAccount(request, id); if (error is not null) return BadRequest(new ProblemDetails { Title = "Account validation failed", Detail = error }); MapAccount(account, request); await db.SaveChangesAsync(); return Ok(account); }
    [HttpGet("accounts/{id}/deliver-to-locations")] public async Task<object> DeliverToLocations(string id) => await db.DeliverToLocations.Where(x => x.ShipToAccountId == id).OrderByDescending(x => x.IsDefault).ThenBy(x => x.Name).ToListAsync();
    [HttpGet("dashboard/messages")] public object Messages() => Enumerable.Range(1, 6).Select(i => new { id = i, title = $"Crop Protection update {i}", snippet = "Demonstration notice for ordering and delivery operations.", timestamp = DateTime.UtcNow.AddHours(-i) });
    [HttpGet("dashboard/knowledge")] public object Knowledge() => new[] { "CPP ordering quick guide", "Understanding availability status", "Freight option reference", "Order confirmation and PDF help", "Customer pickup checklist" }.Select((x, i) => new { id = i + 1, title = x });
    [HttpGet("products/search")] public async Task<object> Products([FromQuery] string? criterion = "Product Name", [FromQuery] string? q = "", [FromQuery] string? query = null, [FromQuery] string? shipToAccountId = null, [FromQuery] bool favorites = false) { q = Normalize(query ?? q ?? ""); var all = await db.Products.ToListAsync(); string Field(Product p) => Criterion(criterion) switch { "itemNumber" => p.ItemNumber, "activeIngredient" => p.ActiveIngredients, "productCategory" => p.Category, "gtin" => p.Gtin, "packageSize" => p.PackageSize, "supplier" => p.Supplier, "productLine" => p.ProductLine, _ => p.Name }; return all.Where(p => (!favorites || p.Favorite) && (q.Length == 0 || Field(p).Contains(q, StringComparison.OrdinalIgnoreCase))).OrderBy(p => Rank(Field(p), q)).ThenBy(p => p.Name); }
    [HttpGet("products/suggestions")] public async Task<object> Suggestions([FromQuery] string? q = null, [FromQuery] string? query = null, [FromQuery] string criterion = "productName", [FromQuery] string? shipToAccountId = null, [FromQuery] int limit = 10) { var normalized = Normalize(query ?? q ?? ""); if (normalized.Length < 2) return new { suggestions = Array.Empty<object>(), products = Array.Empty<Product>(), totalCount = 0 }; var products = ((IEnumerable<Product>)await Products(criterion, normalized, null, shipToAccountId, false)).Take(limit).ToList(); var suggestions = Criterion(criterion) == "activeIngredient" ? products.SelectMany(p => p.ActiveIngredients.Split(',', StringSplitOptions.TrimEntries)).Distinct(StringComparer.OrdinalIgnoreCase).Where(v => v.Contains(normalized, StringComparison.OrdinalIgnoreCase)).Select(v => new { productId = (string?)null, value = v, displayText = v, secondaryText = "Active ingredient", matchType = MatchType(v, normalized) }).Take(limit) : products.Select(p => new { productId = (string?)p.Id, value = Criterion(criterion) == "itemNumber" ? p.ItemNumber : p.Name, displayText = Criterion(criterion) == "itemNumber" ? p.ItemNumber : p.Name, secondaryText = $"{p.Supplier} · {p.PackageSize}", matchType = MatchType(Criterion(criterion) == "itemNumber" ? p.ItemNumber : p.Name, normalized) }); return new { suggestions, products, totalCount = products.Count }; }
    [HttpGet("products/{id}")] public async Task<ActionResult<Product>> Product(string id) => await db.Products.FindAsync(id) is { } p ? p : NotFound();
    [HttpPut("products/{id}/favorite")] public async Task<IActionResult> Favorite(string id) { var p = await db.Products.FindAsync(id); if (p is null) return NotFound(); p.Favorite = !p.Favorite; await db.SaveChangesAsync(); return Ok(p); }
    [HttpGet("orders")] public async Task<object> Orders([FromQuery] string? status = null, [FromQuery] string? q = null) { var os = await db.Orders.OrderByDescending(x => x.SubmittedAt ?? x.UpdatedAt).ToListAsync(); var accts = await db.Accounts.ToDictionaryAsync(x => x.Id); var products = await db.Products.ToDictionaryAsync(x => x.Id); return os.Where(x => status == null || x.Status.ToString().Equals(status, StringComparison.OrdinalIgnoreCase)).Where(x => string.IsNullOrWhiteSpace(q) || x.Id.Contains(q, StringComparison.OrdinalIgnoreCase) || (x.WebOrderNumber?.Contains(q, StringComparison.OrdinalIgnoreCase) ?? false) || (x.CustomerPo?.Contains(q, StringComparison.OrdinalIgnoreCase) ?? false) || (accts.GetValueOrDefault(x.ShipToAccountId)?.Name.Contains(q, StringComparison.OrdinalIgnoreCase) ?? false)).Select(x => new { x.Id, x.WebOrderNumber, status = x.Status.ToString(), x.CustomerPo, x.CreatedAt, x.UpdatedAt, x.SubmittedAt, account = accts.GetValueOrDefault(x.ShipToAccountId), x.Lines, products = x.Lines.Select(line => new { line.ProductId, name = products.GetValueOrDefault(line.ProductId)?.Name ?? "Unavailable product", line.Quantity, line.Uom, line.UnitPrice, total = line.UnitPrice * line.Quantity }), totalQuantity = x.Lines.Sum(line => line.Quantity), totalAmount = x.Lines.Sum(line => line.UnitPrice * line.Quantity), canEdit = CanEdit(x) }); }
    [HttpGet("orders/{id}")] public async Task<ActionResult<Order>> Order(string id) => await db.Orders.FindAsync(id) is { } o ? o : NotFound();
    [HttpPost("orders")] public async Task<object> Save(OrderRequest req) { var o = Map(new Order(), req); db.Orders.Add(o); db.AuditEvents.Add(new() { OrderId = o.Id, EventType = "DraftCreated", Detail = "Draft persisted" }); await db.SaveChangesAsync(); return o; }
    [HttpPut("orders/{id}")] public async Task<IActionResult> Update(string id, OrderRequest req) { var o = await db.Orders.FindAsync(id); if (o is null) return NotFound(); if (!CanEdit(o)) return Conflict(new ProblemDetails { Title = "This order can no longer be edited", Detail = "Submitted, submitting, and cancelled orders are locked by the order lifecycle rules." }); Map(o, req); db.AuditEvents.Add(new() { OrderId = id, EventType = "DraftUpdated", Detail = "Draft fields updated" }); await db.SaveChangesAsync(); return Ok(o); }
    [HttpDelete("orders/{id}")] public async Task<IActionResult> Delete(string id) { var o = await db.Orders.FindAsync(id); if (o is null) return NotFound(); if (o.Status != OrderState.Draft) return Conflict(); db.Remove(o); await db.SaveChangesAsync(); return NoContent(); }
    [HttpPost("orders/{id}/duplicate")] public async Task<IActionResult> Duplicate(string id) { var o = await db.Orders.FindAsync(id); if (o is null) return NotFound(); var copy = new Order { ShipToAccountId = o.ShipToAccountId, SoldToName = o.SoldToName, ContactEmail = o.ContactEmail, ShippingInstructions = o.ShippingInstructions, FreightOption = o.FreightOption, RequestedArrivalDate = DateTime.UtcNow.Date.AddDays(7), Lines = o.Lines }; db.Add(copy); await db.SaveChangesAsync(); return Ok(copy); }
    [HttpPost("orders/{id}/validate")] public async Task<IActionResult> Validate(string id) { var o = await db.Orders.FindAsync(id); if (o is null) return NotFound(); return Ok(await ValidateOrder(o)); }
    [HttpPost("orders/{id}/submit")] public async Task<IActionResult> Submit(string id, [FromHeader(Name = "Idempotency-Key")] string? key) { var o = await db.Orders.FindAsync(id); if (o is null) return NotFound(); if (o.Status == OrderState.Submitted) return Ok(new { o.WebOrderNumber, fulfillmentOrderNumbers = System.Text.Json.JsonSerializer.Deserialize<string[]>(o.FulfillmentOrdersJson) }); var validation = await ValidateOrder(o); if (validation.Any(x => x.Severity == "error")) return UnprocessableEntity(new { title = "Order validation failed", errors = validation }); try { o.Status = OrderState.Submitting; await db.SaveChangesAsync(); var r = await fulfillment.SubmitOrderAsync(o, HttpContext.RequestAborted); o.Status = OrderState.Submitted; o.WebOrderNumber = r.WebOrderNumber; o.SubmittedAt = DateTime.UtcNow; o.FulfillmentOrdersJson = System.Text.Json.JsonSerializer.Serialize(r.FulfillmentOrderNumbers); db.AuditEvents.Add(new() { OrderId = id, EventType = "SubmissionSucceeded", Detail = r.WebOrderNumber }); await db.SaveChangesAsync(); return Ok(r); } catch (Exception ex) { o.Status = OrderState.SubmissionFailed; db.AuditEvents.Add(new() { OrderId = id, EventType = "SubmissionFailed", Detail = ex.Message }); await db.SaveChangesAsync(); return StatusCode(503, new ProblemDetails { Title = "Fulfillment submission failed", Detail = ex.Message }); } }
    [HttpGet("orders/export")] public async Task<IActionResult> Export() { var rows = await db.Orders.ToListAsync(); var csv = "Order ID,Web Order Number,Status,Customer PO\n" + string.Join("\n", rows.Select(x => $"{x.Id},{x.WebOrderNumber},{x.Status},{x.CustomerPo}")); return File(Encoding.UTF8.GetBytes(csv), "text/csv", "cpp-orders.csv"); }
    [HttpGet("orders/{id}/confirmation.pdf")] public async Task<IActionResult> Pdf(string id) { var o = await db.Orders.FindAsync(id); if (o?.Status != OrderState.Submitted) return NotFound(); var text = $"CPP ORDER CONFIRMATION\nWeb Order: {o.WebOrderNumber}\nGenerated: {DateTime.UtcNow:u}\nShip-To: {o.ShipToAccountId}\nPage 1 of 1"; var bytes = SimplePdf(text); db.AuditEvents.Add(new() { OrderId = id, EventType = "ConfirmationDownloaded", Detail = "PDF generated" }); await db.SaveChangesAsync(); return File(bytes, "application/pdf", $"CPP_Order_Confirmation_{o.WebOrderNumber}.pdf"); }
    [HttpPost("assistant/messages")] public async Task<object> Assistant([FromBody] AssistantRequest x) { var m = x.Message.Trim().ToLowerInvariant(); if (m.Contains("glyphosate")) return new { reply = "I found several glyphosate demonstration products. Select an exact SKU before adding it.", products = await db.Products.Where(p => p.ActiveIngredients.Contains("Glyphosate")).Take(5).ToListAsync() }; if (m.Contains("sterling")) return new { reply = "I found Sterling Blue options. Which exact SKU would you like?", products = await db.Products.Where(p => p.Name.Contains("Sterling Blue")).ToListAsync() }; if (m.Contains("review")) return new { reply = "Your structured draft is ready to review in the standard order workflow." }; if (m.Contains("submit")) return new { reply = "Submission always requires explicit confirmation on the review page." }; return new { reply = "I can create a CPP order, find products, change quantity, choose a Ship-To, or show your draft. Tell me the product or account to begin." }; }
    async Task<List<ValidationResult>> ValidateOrder(Order o) { var a = await db.Accounts.FindAsync(o.ShipToAccountId); var products = await db.Products.ToDictionaryAsync(x => x.Id); var result = rules.Validate(new(o.Id, o.ShipToAccountId, o.DeliverToAccountId, o.CustomerPo, o.ContactEmail, o.ShippingInstructions, o.CustomerPickup, o.FreightOption, o.RequestedArrivalDate, o.Lines, o.DeliverToAnotherLocation, o.AlternateDelivery), a, products); if (o.DeliverToAnotherLocation && (o.AlternateDelivery is null || string.IsNullOrWhiteSpace(o.AlternateDelivery.LocationName) || string.IsNullOrWhiteSpace(o.AlternateDelivery.AddressLine1) || string.IsNullOrWhiteSpace(o.AlternateDelivery.City) || string.IsNullOrWhiteSpace(o.AlternateDelivery.State) || string.IsNullOrWhiteSpace(o.AlternateDelivery.PostalCode))) result.Add(new("error", "ALTERNATE_DELIVERY", "Complete all required alternate delivery address fields.", "alternateDelivery")); return result; }
    static Order Map(Order o, OrderRequest r) { o.ShipToAccountId = r.ShipToAccountId; o.DeliverToAccountId = r.DeliverToAnotherLocation ? null : r.DeliverToAccountId; o.DeliverToAnotherLocation = r.DeliverToAnotherLocation; o.AlternateDelivery = r.DeliverToAnotherLocation ? r.AlternateDelivery : null; o.CustomerPo = r.CustomerPo; o.ContactEmail = r.ContactEmail; o.ShippingInstructions = r.ShippingInstructions; o.CustomerPickup = r.CustomerPickup; o.FreightOption = r.FreightOption; o.RequestedArrivalDate = r.RequestedArrivalDate; o.Lines = r.Lines; o.UpdatedAt = DateTime.UtcNow; o.Status = OrderState.Draft; return o; }
    static bool CanEdit(Order order) => order.Status is not (OrderState.Submitted or OrderState.Submitting or OrderState.Cancelled);
    async Task<string?> ValidateAccount(AccountRequest request, string? currentId = null) { if (string.IsNullOrWhiteSpace(request.AccountNumber) || string.IsNullOrWhiteSpace(request.Name) || string.IsNullOrWhiteSpace(request.Address) || string.IsNullOrWhiteSpace(request.City) || string.IsNullOrWhiteSpace(request.State) || string.IsNullOrWhiteSpace(request.PostalCode) || string.IsNullOrWhiteSpace(request.SoldToName)) return "Account number, name, address, city, state, postal code, and Sold-To name are required."; if (!string.IsNullOrWhiteSpace(request.ContactEmail) && !request.ContactEmail.Contains('@')) return "Contact email must be valid."; if (await db.Accounts.AnyAsync(x => x.AccountNumber == request.AccountNumber.Trim() && x.Id != currentId)) return "Account number already exists."; return null; }
    static Account MapAccount(Account account, AccountRequest request) { account.AccountNumber = request.AccountNumber.Trim(); account.Name = request.Name.Trim(); account.Address = request.Address.Trim(); account.City = request.City.Trim(); account.State = request.State.Trim().ToUpperInvariant(); account.PostalCode = request.PostalCode.Trim(); account.SoldToName = request.SoldToName.Trim(); account.ContactEmail = request.ContactEmail.Trim(); account.ShippingInstructions = request.ShippingInstructions.Trim(); account.RequiresCustomerPo = request.RequiresCustomerPo; return account; }
    static string Normalize(string value) => string.Join(' ', value.Trim().Split(' ', StringSplitOptions.RemoveEmptyEntries));
    static string Criterion(string? value) => value?.Replace(" ", "").Replace("/", "").ToLowerInvariant() switch { "itemnumber" => "itemNumber", "activeingredient" => "activeIngredient", "productcategory" => "productCategory", "gtin" => "gtin", "packagesize" => "packageSize", "vendorsupplier" or "supplier" => "supplier", "productline" => "productLine", _ => "productName" };
    static int Rank(string value, string query) { if (value.Equals(query, StringComparison.OrdinalIgnoreCase)) return 0; if (value.StartsWith(query, StringComparison.OrdinalIgnoreCase)) return 1; if (value.Split(' ', StringSplitOptions.RemoveEmptyEntries).Any(x => x.StartsWith(query, StringComparison.OrdinalIgnoreCase))) return 2; return 3; }
    static string MatchType(string value, string query) => Rank(value, query) switch { 0 => "exact", 1 => "startsWith", 2 => "wordStartsWith", _ => "contains" };
    static byte[] SimplePdf(string text) { var clean = text.Replace("(", "[").Replace(")", "]").Replace("\n", ") Tj 0 -18 Td ("); var stream = $"BT /F1 12 Tf 72 740 Td ({clean}) Tj ET"; var body = $"%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj\n4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n5 0 obj<</Length {stream.Length}>>stream\n{stream}\nendstream endobj\nxref\n0 6\n0000000000 65535 f \ntrailer<</Root 1 0 R/Size 6>>\nstartxref\n0\n%%EOF"; return Encoding.ASCII.GetBytes(body); }
}
public record AssistantRequest(string Message, string? OrderId);
