using System.ComponentModel.DataAnnotations;
using System.Text.Json;

namespace Cpp.Api;

public enum OrderState { New, Draft, ReadyForReview, Validating, ValidationFailed, ReadyForSubmission, Submitting, Submitted, SubmissionFailed, Cancelled }
public record CurrentUser(string Id, string UserName, string DisplayName, string Role, bool CanViewPricing, bool CanViewStoplight);
public class Account { [Key] public string Id { get; set; } = ""; public string AccountNumber { get; set; } = ""; public string Name { get; set; } = ""; public string Address { get; set; } = ""; public string City { get; set; } = ""; public string State { get; set; } = "MO"; public string PostalCode { get; set; } = ""; public string SoldToName { get; set; } = ""; public string ContactEmail { get; set; } = ""; public string ShippingInstructions { get; set; } = ""; public bool RequiresCustomerPo { get; set; } }
public record AccountRequest(string AccountNumber, string Name, string Address, string City, string State, string PostalCode, string SoldToName, string ContactEmail, string ShippingInstructions, bool RequiresCustomerPo);
public class DeliverToLocation { [Key] public string Id { get; set; } = ""; public string AccountNumber { get; set; } = ""; public string Name { get; set; } = ""; public string AddressLine1 { get; set; } = ""; public string AddressLine2 { get; set; } = ""; public string City { get; set; } = ""; public string State { get; set; } = "MO"; public string PostalCode { get; set; } = ""; public string ContactName { get; set; } = ""; public string ContactPhone { get; set; } = ""; public bool IsDefault { get; set; } public string ShipToAccountId { get; set; } = ""; }
public record AlternateDeliveryLocation(string LocationName, string AddressLine1, string? AddressLine2, string City, string State, string PostalCode, string ContactName, string ContactPhone);
public class Product { [Key] public string Id { get; set; } = ""; public string ItemNumber { get; set; } = ""; public string Name { get; set; } = ""; public string ShortName { get; set; } = ""; public string Supplier { get; set; } = ""; public string Category { get; set; } = ""; public string ProductLine { get; set; } = ""; public string ActiveIngredients { get; set; } = ""; public string Gtin { get; set; } = ""; public string PackageSize { get; set; } = ""; public string Uom { get; set; } = "CS"; public decimal Price { get; set; } public string PriceUom { get; set; } = "CS"; public string LeadTimeText { get; set; } = "3 business days"; public int MinimumQuantity { get; set; } = 1; public int MaximumQuantity { get; set; } = 9999; public int QuantityIncrement { get; set; } = 1; public bool Favorite { get; set; } public string Restrictions { get; set; } = "Review product label before use"; public bool Orderable { get; set; } = true; public int AvailableInventory { get; set; } public string StoplightStatus { get; set; } = "Available"; }
public class Order { [Key] public string Id { get; set; } = Guid.NewGuid().ToString("N")[..10].ToUpperInvariant(); public string? WebOrderNumber { get; set; } public OrderState Status { get; set; } = OrderState.Draft; public string UserId { get; set; } = "u1"; public string ShipToAccountId { get; set; } = ""; public string SoldToName { get; set; } = ""; public string? DeliverToAccountId { get; set; } public bool DeliverToAnotherLocation { get; set; } public string? AlternateDeliveryJson { get; set; } public string? CustomerPo { get; set; } public string ContactEmail { get; set; } = ""; public string ShippingInstructions { get; set; } = ""; public bool CustomerPickup { get; set; } public string FreightOption { get; set; } = "Standard"; public DateTime RequestedArrivalDate { get; set; } = DateTime.UtcNow.Date.AddDays(7); public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; public DateTime? SubmittedAt { get; set; } public string LinesJson { get; set; } = "[]"; public string FulfillmentOrdersJson { get; set; } = "[]"; [System.ComponentModel.DataAnnotations.Schema.NotMapped] public List<OrderLineDto> Lines { get => JsonSerializer.Deserialize<List<OrderLineDto>>(LinesJson) ?? []; set => LinesJson = JsonSerializer.Serialize(value); } [System.ComponentModel.DataAnnotations.Schema.NotMapped] public AlternateDeliveryLocation? AlternateDelivery { get => string.IsNullOrWhiteSpace(AlternateDeliveryJson) ? null : JsonSerializer.Deserialize<AlternateDeliveryLocation>(AlternateDeliveryJson); set => AlternateDeliveryJson = value is null ? null : JsonSerializer.Serialize(value); } }
public record OrderLineDto(string ProductId, int Quantity, string Uom, decimal UnitPrice, DateTime RequestedArrivalDate, string InventorySource = "ASC");
public record OrderRequest(string? Id, string ShipToAccountId, string? DeliverToAccountId, string? CustomerPo, string ContactEmail, string ShippingInstructions, bool CustomerPickup, string FreightOption, DateTime RequestedArrivalDate, List<OrderLineDto> Lines, bool DeliverToAnotherLocation = false, AlternateDeliveryLocation? AlternateDelivery = null);
public record ValidationResult(string Severity, string Code, string Message, string? Field = null, string? SuggestedResolution = null);
public record SubmissionResult(string WebOrderNumber, IReadOnlyList<string> FulfillmentOrderNumbers, string? SplitReason);
public class AuditEvent { [Key] public long Id { get; set; } public string OrderId { get; set; } = ""; public string EventType { get; set; } = ""; public DateTime OccurredAt { get; set; } = DateTime.UtcNow; public string Detail { get; set; } = ""; }
